#!/usr/bin/env node
/**
 * Split ShapeLibraryData.js into per-category data files
 *
 * Reads the existing monolithic ShapeLibraryData.js and produces:
 *   1. A new, lightweight ShapeLibraryData.js (categories + shape index, no SVG)
 *   2. Per-category data files: ShapeLibraryData.{categoryId}.js
 *
 * This enables the shape library panel to lazy-load shapes per category,
 * dramatically reducing the initial load from 4+ MB to ~350 KB.
 *
 * Usage: node split-library.js
 */

'use strict';

const vm = require( 'vm' );
const fs = require( 'fs' );
const path = require( 'path' );

const SOURCE_FILE = path.join( __dirname, '../ShapeLibraryData.js' );
const OUTPUT_DIR = path.join( __dirname, '..' );

// ---------------------------------------------------------------------------
// Step 1: Evaluate the existing ShapeLibraryData.js in a sandboxed context
// ---------------------------------------------------------------------------
const source = fs.readFileSync( SOURCE_FILE, 'utf8' );

const sandbox = {
	window: {
		Layers: {
			ShapeLibrary: {}
		}
	}
};

vm.createContext( sandbox );

try {
	vm.runInContext( source, sandbox );
} catch ( e ) {
	console.error( 'Failed to evaluate ShapeLibraryData.js:', e.message );
	process.exit( 1 );
}

const lib = sandbox.window.Layers.ShapeLibrary;

if ( typeof lib.getCategories !== 'function' || typeof lib.getAllShapes !== 'function' ) {
	console.error( 'ShapeLibraryData.js did not expose expected API methods.' );
	process.exit( 1 );
}

const categories = lib.getCategories();
const allShapes = lib.getAllShapes();

console.log( `Loaded ${ allShapes.length } shapes across ${ categories.filter( ( c ) => !c.isParent ).length } leaf categories.\n` );

// ---------------------------------------------------------------------------
// Step 2: Group shapes by category
// ---------------------------------------------------------------------------
const byCategory = {};
for ( const shape of allShapes ) {
	if ( !byCategory[ shape.category ] ) {
		byCategory[ shape.category ] = [];
	}
	byCategory[ shape.category ].push( shape );
}

// ---------------------------------------------------------------------------
// Step 3: Generate per-category data files
// ---------------------------------------------------------------------------

/**
 * Escape a string value for embedding in a single-quoted JS string literal.
 *
 * @param {string} str
 * @return {string}
 */
function escapeJS( str ) {
	return str
		.replace( /\\/g, '\\\\' )
		.replace( /'/g, "\\'" )
		.replace( /\n/g, '\\n' )
		.replace( /\r/g, '' );
}

let totalWritten = 0;

for ( const [ catId, shapes ] of Object.entries( byCategory ) ) {
	let fileContent = `/**
 * Shape Library Data - ${ catId } category
 *
 * Auto-generated by split-library.js — do not edit manually.
 * Source: ShapeLibraryData.js (split on ${ new Date().toISOString().slice( 0, 10 ) })
 *
 * Contains ${ shapes.length } shapes.
 *
 * @file
 */

( function () {
\t'use strict';

\twindow.Layers = window.Layers || {};
\twindow.Layers.ShapeLibrary = window.Layers.ShapeLibrary || {};

\tif ( typeof window.Layers.ShapeLibrary.registerCategoryShapes !== 'function' ) {
\t\t// Base module not yet loaded — defer silently
\t\treturn;
\t}

\twindow.Layers.ShapeLibrary.registerCategoryShapes( '${ catId }', [
`;

	for ( const shape of shapes ) {
		fileContent += `\t\t{
\t\t\tid: '${ escapeJS( shape.id ) }',
\t\t\tcategory: '${ shape.category }',
\t\t\tname: '${ escapeJS( shape.name ) }',
\t\t\ttags: ${ JSON.stringify( shape.tags ) },
\t\t\tviewBox: ${ JSON.stringify( shape.viewBox ) },
\t\t\tsvg: '${ escapeJS( shape.svg ) }'
\t\t},
`;
	}

	fileContent += `\t] );
}() );
`;

	const outFile = path.join( OUTPUT_DIR, `ShapeLibraryData.${ catId }.js` );
	fs.writeFileSync( outFile, fileContent, 'utf8' );
	const kb = ( fs.statSync( outFile ).size / 1024 ).toFixed( 1 );
	console.log( `  ${ catId.padEnd( 14 ) } ${ String( shapes.length ).padStart( 4 ) } shapes  →  ShapeLibraryData.${ catId }.js  (${ kb } KB)` );
	totalWritten++;
}

// ---------------------------------------------------------------------------
// Step 4: Build the lightweight SHAPE_INDEX (no SVG, no viewBox)
// ---------------------------------------------------------------------------
const indexEntries = allShapes.map( ( s ) =>
	`\t\t{ id: '${ escapeJS( s.id ) }', category: '${ s.category }', name: '${ escapeJS( s.name ) }', tags: ${ JSON.stringify( s.tags ) } }`
).join( ',\n' );

// ---------------------------------------------------------------------------
// Step 5: Serialise the CATEGORIES array from the live data
// ---------------------------------------------------------------------------
let categoriesJS = '';
for ( const cat of categories ) {
	categoriesJS += '\t\t{\n';
	categoriesJS += `\t\t\tid: '${ cat.id }',\n`;
	categoriesJS += `\t\t\tname: '${ escapeJS( cat.name ) }',\n`;
	if ( cat.prefix !== undefined ) {
		categoriesJS += `\t\t\tprefix: '${ escapeJS( cat.prefix ) }',\n`;
	}
	categoriesJS += `\t\t\tcolor: '${ cat.color }',\n`;
	categoriesJS += `\t\t\tdescription: '${ escapeJS( cat.description ) }'`;
	if ( cat.isParent ) {
		categoriesJS += `,\n\t\t\tisParent: true`;
	}
	if ( cat.parentId ) {
		categoriesJS += `,\n\t\t\tparentId: '${ cat.parentId }'`;
	}
	categoriesJS += '\n\t\t},\n';
}

// ---------------------------------------------------------------------------
// Step 6: Write the new lightweight base ShapeLibraryData.js
// ---------------------------------------------------------------------------
const baseContent = `/**
 * Shape Library Data for Layers Extension
 *
 * Auto-generated by split-library.js — do not edit manually.
 * Generated: ${ new Date().toISOString() }
 *
 * Contains category metadata and a shape index (${ allShapes.length } shapes).
 * SVG data is NOT included here — it is loaded lazily per category via
 * separate ResourceLoader modules (ext.layers.shapeLibrary.data.*).
 *
 * @file
 */

( function () {
\t'use strict';

\t/**
\t * Shape library categories
\t *
\t * @type {Object[]}
\t */
\tconst CATEGORIES = [
${ categoriesJS }\t];

\t/**
\t * Lightweight shape index — id, category, name, tags only (no SVG).
\t * Used for fast cross-category search without loading SVG data.
\t *
\t * @type {Object[]}
\t */
\tconst SHAPE_INDEX = [
${ indexEntries }
\t];

\t/**
\t * Per-category SVG shape store.
\t * Populated lazily when category data modules are loaded via mw.loader.using().
\t *
\t * @type {Object.<string, Object[]>}
\t */
\tconst _loaded = {};

\t/**
\t * Shape Library API
\t *
\t * @namespace
\t */
\twindow.Layers = window.Layers || {};
\twindow.Layers.ShapeLibrary = window.Layers.ShapeLibrary || {};

\t// Extend ShapeLibrary with data methods (preserves CustomShapeRenderer if already attached)
\tObject.assign( window.Layers.ShapeLibrary, {

\t\t/**
\t\t * Get all categories
\t\t *
\t\t * @return {Object[]} Array of category objects
\t\t */
\t\tgetCategories: function () {
\t\t\treturn CATEGORIES;
\t\t},

\t\t/**
\t\t * Register shape data for a category (called by per-category data modules).
\t\t *
\t\t * @param {string} categoryId - Category ID
\t\t * @param {Object[]} shapes - Array of shape objects with full SVG data
\t\t */
\t\tregisterCategoryShapes: function ( categoryId, shapes ) {
\t\t\t_loaded[ categoryId ] = shapes;
\t\t},

\t\t/**
\t\t * Check whether SVG data for a category has been loaded.
\t\t *
\t\t * @param {string} categoryId - Category ID
\t\t * @return {boolean}
\t\t */
\t\tisCategoryLoaded: function ( categoryId ) {
\t\t\treturn Boolean( _loaded[ categoryId ] );
\t\t},

\t\t/**
\t\t * Get shapes with full SVG data for a category.
\t\t * Returns an empty array if the category data module has not yet been loaded.
\t\t *
\t\t * @param {string} categoryId - Category ID
\t\t * @return {Object[]} Array of full shape objects (empty if not yet loaded)
\t\t */
\t\tgetShapesByCategory: function ( categoryId ) {
\t\t\treturn _loaded[ categoryId ] || [];
\t\t},

\t\t/**
\t\t * Get all loaded shapes (only categories whose data has been fetched).
\t\t *
\t\t * @return {Object[]}
\t\t */
\t\tgetAllShapes: function () {
\t\t\treturn Object.values( _loaded ).flat();
\t\t},

\t\t/**
\t\t * Get a shape by ID from any loaded category.
\t\t *
\t\t * @param {string} shapeId - Shape ID
\t\t * @return {Object|null} Shape object or null
\t\t */
\t\tgetShape: function ( shapeId ) {
\t\t\tfor ( const shapes of Object.values( _loaded ) ) {
\t\t\t\tconst found = shapes.find( ( s ) => s.id === shapeId );
\t\t\t\tif ( found ) {
\t\t\t\t\treturn found;
\t\t\t\t}
\t\t\t}
\t\t\treturn null;
\t\t},

\t\t/**
\t\t * Search shapes by query string.
\t\t *
\t\t * Uses the full SHAPE_INDEX for metadata matching (always available), then
\t\t * enriches results with full SVG data if the category has been loaded.
\t\t *
\t\t * @param {string} query - Search query (min 2 chars)
\t\t * @return {Object[]} Matching shape objects (may lack svg/viewBox if not yet loaded)
\t\t */
\t\tsearch: function ( query ) {
\t\t\tif ( !query || query.length < 2 ) {
\t\t\t\treturn [];
\t\t\t}
\t\t\tconst q = query.toLowerCase();
\t\t\tconst matches = SHAPE_INDEX.filter( ( s ) => {
\t\t\t\tif ( s.name.toLowerCase().includes( q ) ) {
\t\t\t\t\treturn true;
\t\t\t\t}
\t\t\t\treturn s.tags.some( ( tag ) => tag.includes( q ) );
\t\t\t} );
\t\t\t// Enrich with full SVG data for already-loaded categories
\t\t\treturn matches.map( ( s ) => {
\t\t\t\tif ( _loaded[ s.category ] ) {
\t\t\t\t\tconst full = _loaded[ s.category ].find( ( f ) => f.id === s.id );
\t\t\t\t\tif ( full ) {
\t\t\t\t\t\treturn full;
\t\t\t\t\t}
\t\t\t\t}
\t\t\t\treturn s; // Return metadata-only object (no svg/viewBox) if not loaded yet
\t\t\t} );
\t\t},

\t\t/**
\t\t * Get the total number of shapes (from the index, regardless of load state).
\t\t *
\t\t * @return {number}
\t\t */
\t\tgetCount: function () {
\t\t\treturn SHAPE_INDEX.length;\t\t},

\t\t/**
\t\t * Get the number of shapes in a category (from the index, always available).
\t\t *
\t\t * @param {string} categoryId - Category ID
\t\t * @return {number}
\t\t */
\t\tgetCategoryCount: function ( categoryId ) {
\t\t\treturn SHAPE_INDEX.filter( ( s ) => s.category === categoryId ).length;\t\t}
\t} );
}() );
`;

const baseFile = path.join( OUTPUT_DIR, 'ShapeLibraryData.js' );
// Back up the original before overwriting
const backupFile = path.join( OUTPUT_DIR, 'ShapeLibraryData.original.js' );
if ( !fs.existsSync( backupFile ) ) {
	fs.copyFileSync( baseFile, backupFile );
	console.log( `\nBacked up original → ShapeLibraryData.original.js` );
}
fs.writeFileSync( baseFile, baseContent, 'utf8' );

const baseKB = ( fs.statSync( baseFile ).size / 1024 ).toFixed( 1 );
console.log( `\nWrote new base ShapeLibraryData.js  (${ baseKB } KB, was 4190 KB)` );
console.log( `Wrote ${ totalWritten } per-category data files.` );
console.log( '\nDone. Next steps:' );
console.log( '  1. Update extension.json with the new per-category ResourceLoader modules.' );
console.log( '  2. Update ShapeLibraryPanel.js to use mw.loader.using() per category.' );
