name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What are you trying to accomplish?
      placeholder: I'm trying to... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution. How should this feature work?
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches or workarounds?
      placeholder: I've tried... / An alternative could be...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the extension would this affect?
      options:
        - Editor (canvas, tools, drawing)
        - Layer Panel (layer list, properties)
        - Toolbar (buttons, controls)
        - Viewer (lightbox, article display)
        - API (save, load, delete)
        - Wikitext Integration
        - New Component
        - Other/Unknown
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Blocking my use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to this feature?
      options:
        - label: I'd like to implement this myself (with guidance)
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Any mockups, screenshots, or examples from other tools?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful?
