/**
 * Tests for IdGenerator utility
 */
'use strict';

const IdGenerator = require( '../../../resources/ext.layers.shared/IdGenerator.js' );

describe( 'IdGenerator', () => {
	beforeEach( () => {
		IdGenerator._resetForTesting();
	} );

	describe( 'generateLayerId', () => {
		it( 'should generate a string starting with layer_', () => {
			const id = IdGenerator.generateLayerId();
			expect( id.startsWith( 'layer_' ) ).toBe( true );
		} );

		it( 'should generate unique IDs on successive calls', () => {
			const ids = new Set();
			for ( let i = 0; i < 1000; i++ ) {
				ids.add( IdGenerator.generateLayerId() );
			}
			expect( ids.size ).toBe( 1000 );
		} );

		it( 'should generate IDs matching expected format', () => {
			const id = IdGenerator.generateLayerId();
			// Format: layer_{timestamp}_{sessionId}{counter}_{random}
			expect( id ).toMatch( /^layer_\d+_[a-z0-9]+\d+_[a-z0-9]+$/ );
		} );

		it( 'should increment session counter', () => {
			expect( IdGenerator.getSessionCounter() ).toBe( 0 );
			IdGenerator.generateLayerId();
			expect( IdGenerator.getSessionCounter() ).toBe( 1 );
			IdGenerator.generateLayerId();
			expect( IdGenerator.getSessionCounter() ).toBe( 2 );
		} );
	} );

	describe( 'generateId', () => {
		it( 'should use custom prefix', () => {
			const id = IdGenerator.generateId( 'group' );
			expect( id.startsWith( 'group_' ) ).toBe( true );
		} );

		it( 'should default to id_ prefix', () => {
			const id = IdGenerator.generateId();
			expect( id.startsWith( 'id_' ) ).toBe( true );
		} );

		it( 'should generate unique IDs with same prefix', () => {
			const ids = new Set();
			for ( let i = 0; i < 100; i++ ) {
				ids.add( IdGenerator.generateId( 'test' ) );
			}
			expect( ids.size ).toBe( 100 );
		} );
	} );

	describe( 'isValidLayerId', () => {
		it( 'should return true for valid layer IDs', () => {
			expect( IdGenerator.isValidLayerId( 'layer_123' ) ).toBe( true );
			expect( IdGenerator.isValidLayerId( 'layer_abc_def' ) ).toBe( true );
			expect( IdGenerator.isValidLayerId( 'layer_1234567890_abc123_xyz' ) ).toBe( true );
		} );

		it( 'should return false for invalid layer IDs', () => {
			expect( IdGenerator.isValidLayerId( '' ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( null ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( undefined ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( 123 ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( 'notlayer_123' ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( 'layer-123' ) ).toBe( false ); // hyphens not allowed
		} );

		it( 'should validate IDs generated by generateLayerId', () => {
			for ( let i = 0; i < 10; i++ ) {
				const id = IdGenerator.generateLayerId();
				expect( IdGenerator.isValidLayerId( id ) ).toBe( true );
			}
		} );
	} );

	describe( 'uniqueness under rapid generation', () => {
		it( 'should generate unique IDs even when called rapidly in a loop', () => {
			const ids = [];
			const startTime = Date.now();

			// Generate many IDs as fast as possible
			while ( Date.now() - startTime < 10 ) {
				ids.push( IdGenerator.generateLayerId() );
			}

			// All should be unique
			const uniqueIds = new Set( ids );
			expect( uniqueIds.size ).toBe( ids.length );
		} );
	} );

	describe( 'getSessionCounter', () => {
		it( 'should return current counter value', () => {
			expect( IdGenerator.getSessionCounter() ).toBe( 0 );
			IdGenerator.generateLayerId();
			IdGenerator.generateLayerId();
			IdGenerator.generateLayerId();
			expect( IdGenerator.getSessionCounter() ).toBe( 3 );
		} );
	} );

	describe( '_resetForTesting', () => {
		it( 'should reset counter to 0', () => {
			IdGenerator.generateLayerId();
			IdGenerator.generateLayerId();
			expect( IdGenerator.getSessionCounter() ).toBe( 2 );
			IdGenerator._resetForTesting();
			expect( IdGenerator.getSessionCounter() ).toBe( 0 );
		} );
	} );
} );
