'use strict';

const IdGenerator = require( '../../resources/ext.layers.shared/IdGenerator.js' );

describe( 'IdGenerator', () => {
	beforeEach( () => {
		IdGenerator._resetForTesting();
	} );

	describe( 'generateLayerId', () => {
		it( 'should return a string starting with layer_', () => {
			const id = IdGenerator.generateLayerId();
			expect( id ).toMatch( /^layer_/ );
		} );

		it( 'should generate unique IDs on subsequent calls', () => {
			const id1 = IdGenerator.generateLayerId();
			const id2 = IdGenerator.generateLayerId();
			expect( id1 ).not.toBe( id2 );
		} );

		it( 'should contain a timestamp component', () => {
			const before = Date.now();
			const id = IdGenerator.generateLayerId();
			const after = Date.now();
			// Extract timestamp from: layer_{timestamp}_{sessionId}{counter}_{random}
			const parts = id.split( '_' );
			const timestamp = parseInt( parts[ 1 ], 10 );
			expect( timestamp ).toBeGreaterThanOrEqual( before );
			expect( timestamp ).toBeLessThanOrEqual( after );
		} );

		it( 'should increment the session counter', () => {
			const counterBefore = IdGenerator.getSessionCounter();
			IdGenerator.generateLayerId();
			expect( IdGenerator.getSessionCounter() ).toBe( counterBefore + 1 );
		} );

		it( 'should match the expected format', () => {
			const id = IdGenerator.generateLayerId();
			// layer_{digits}_{alphanumeric}
			expect( id ).toMatch( /^layer_\d+_[a-z0-9]+_[a-z0-9]+$/ );
		} );
	} );

	describe( 'generateId', () => {
		it( 'should use the provided prefix', () => {
			const id = IdGenerator.generateId( 'group' );
			expect( id ).toMatch( /^group_/ );
		} );

		it( 'should default to "id" prefix when none provided', () => {
			const id = IdGenerator.generateId();
			expect( id ).toMatch( /^id_/ );
		} );

		it( 'should default to "id" prefix when prefix is empty string', () => {
			const id = IdGenerator.generateId( '' );
			expect( id ).toMatch( /^id_/ );
		} );

		it( 'should default to "id" prefix when prefix is null', () => {
			const id = IdGenerator.generateId( null );
			expect( id ).toMatch( /^id_/ );
		} );

		it( 'should default to "id" prefix when prefix is undefined', () => {
			const id = IdGenerator.generateId( undefined );
			expect( id ).toMatch( /^id_/ );
		} );

		it( 'should generate unique IDs', () => {
			const id1 = IdGenerator.generateId( 'test' );
			const id2 = IdGenerator.generateId( 'test' );
			expect( id1 ).not.toBe( id2 );
		} );

		it( 'should increment the session counter', () => {
			const counterBefore = IdGenerator.getSessionCounter();
			IdGenerator.generateId( 'x' );
			expect( IdGenerator.getSessionCounter() ).toBe( counterBefore + 1 );
		} );
	} );

	describe( 'isValidLayerId', () => {
		it( 'should return true for valid layer IDs', () => {
			expect( IdGenerator.isValidLayerId( 'layer_123_abc1_def' ) ).toBe( true );
		} );

		it( 'should return true for simple layer IDs', () => {
			expect( IdGenerator.isValidLayerId( 'layer_1' ) ).toBe( true );
		} );

		it( 'should return true for IDs generated by generateLayerId', () => {
			const id = IdGenerator.generateLayerId();
			expect( IdGenerator.isValidLayerId( id ) ).toBe( true );
		} );

		it( 'should return false for non-string input', () => {
			expect( IdGenerator.isValidLayerId( 123 ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( null ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( undefined ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( {} ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( [] ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( true ) ).toBe( false );
		} );

		it( 'should return false for empty string', () => {
			expect( IdGenerator.isValidLayerId( '' ) ).toBe( false );
		} );

		it( 'should return false for IDs not starting with layer_', () => {
			expect( IdGenerator.isValidLayerId( 'group_123' ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( 'id_123' ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( '123' ) ).toBe( false );
		} );

		it( 'should return false for IDs with invalid characters', () => {
			expect( IdGenerator.isValidLayerId( 'layer_abc-def' ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( 'layer_abc.def' ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( 'layer_abc def' ) ).toBe( false );
			expect( IdGenerator.isValidLayerId( 'layer_abc$def' ) ).toBe( false );
		} );

		it( 'should return false for just the prefix', () => {
			expect( IdGenerator.isValidLayerId( 'layer_' ) ).toBe( false );
		} );
	} );

	describe( 'getSessionCounter', () => {
		it( 'should return 0 after reset', () => {
			expect( IdGenerator.getSessionCounter() ).toBe( 0 );
		} );

		it( 'should track cumulative calls across generators', () => {
			IdGenerator.generateLayerId();
			IdGenerator.generateId( 'test' );
			IdGenerator.generateLayerId();
			expect( IdGenerator.getSessionCounter() ).toBe( 3 );
		} );
	} );

	describe( '_resetForTesting', () => {
		it( 'should reset counter to 0', () => {
			IdGenerator.generateLayerId();
			IdGenerator.generateLayerId();
			expect( IdGenerator.getSessionCounter() ).toBe( 2 );
			IdGenerator._resetForTesting();
			expect( IdGenerator.getSessionCounter() ).toBe( 0 );
		} );
	} );

	describe( 'window.Layers namespace export', () => {
		it( 'should export functions to window.Layers.Utils', () => {
			expect( window.Layers ).toBeDefined();
			expect( window.Layers.Utils ).toBeDefined();
			expect( typeof window.Layers.Utils.generateLayerId ).toBe( 'function' );
			expect( typeof window.Layers.Utils.generateId ).toBe( 'function' );
			expect( typeof window.Layers.Utils.isValidLayerId ).toBe( 'function' );
			expect( typeof window.Layers.Utils.getSessionCounter ).toBe( 'function' );
		} );
	} );
} );
