'use strict';
const Client = require( '../../resources/ext.layers.editor/PageOwnedPdfEditorReadClient.js' );
const copy = value => JSON.parse( JSON.stringify( value ) );
const request = () => ( { owner: 'Example_owner', revisionId: 12, binding: 'v1:77:anchor', page: 2 } );
function context( stored = true ) {
	return { owner: 'Example_owner', pageId: 77, revisionId: 12, binding: 'v1:77:anchor', kind: 'pdf', label: 'ABC',
		initialPage: 2, pageCount: 3, page: stored ? 2 : 1, members: [ { page: 2, surfaceId: 'anchor' } ], stored,
		surface: { id: stored ? 'anchor' : 'new-member', kind: 'pdf', label: 'ABC', source: { repository: 'local',
			fileTitle: 'File:Example.pdf', timestamp: '20261007120000', sha1: 'a'.repeat( 31 ), page: stored ? 2 : 1, extra: null },
			canvas: { width: 333, height: 111, backgroundVisible: false, backgroundOpacity: 0, backgroundColor: 'invalid-finite-color' },
			layers: stored ? [ { id: 'keep', type: 'unknown-finite', x: -17, y: 29, gradient: { type: 'linear', angle: 999,
				colors: [ { offset: 0, color: '#ff0000' }, { offset: 1, color: '#00ff00' } ] } } ] : [],
			metadata: { nested: [ false, null, 0 ] } },
		sourceGeometry: { page: stored ? 2 : 1, width: stored ? 416 : 208, height: stored ? 208 : 416, units: 'file-handler-pixels' },
		rendition: { url: '/test-files/exact/page.png', width: 333, height: 166, extra: null }, extra: { preserved: true } };
}
const setup = data => { const api = { get: jest.fn().mockResolvedValue( { layersread: { editor: data } } ), postWithToken: jest.fn() }; return { api, client: new Client( api ) }; };
describe( 'Unregistered exact PDF editor read client', () => {
	it.each( [ true, false ] )( 'requests exact stored=%s page and preserves complete finite payload without repair', async stored => {
		const data = context( stored ), expected = copy( data ), options = { ...request(), page: data.page }, { client, api } = setup( data );
		const result = await client.read( options ); expect( result ).toStrictEqual( expected ); expect( api.get ).toHaveBeenCalledTimes( 1 ); expect( api.get ).toHaveBeenCalledWith( { action: 'layersread', formatversion: 2, owner: options.owner, revid: 12, binding: options.binding, editorpage: options.page } );
		result.surface.canvas.width = 999; result.surface.source.extra = 'caller'; result.members[ 0 ].page = 99; result.extra.preserved = false; expect( data ).toStrictEqual( expected ); expect( await client.read( options ) ).toStrictEqual( expected ); expect( api.get ).toHaveBeenCalledTimes( 2 ); expect( api.postWithToken ).not.toHaveBeenCalled();
	} );
	it( 'captures request primitives before pending transport and returns no shared references', async () => {
		let resolve; const data = context(), api = { get: jest.fn( () => new Promise( done => { resolve = done; } ) ) }, options = request(), pending = new Client( api ).read( options ); options.owner = 'Other'; options.page = 1; options.binding = 'Other'; options.revisionId = 15; resolve( { layersread: { editor: data } } ); expect( await pending ).toStrictEqual( data ); expect( api.get ).toHaveBeenCalledTimes( 1 );
	} );
	it( 'rejects a structurally valid context for another requested page', async () => {
		const data = context( false ), { client, api } = setup( data ); let result, refused = false; try { result = await client.read( request() ); } catch ( error ) { refused = true; expect( error ).toMatchObject( { code: 'layers-reading-failed', message: 'layers-reading-failed' } ); }
		expect( result ).toBeUndefined(); expect( refused ).toBe( true ); expect( api.get ).toHaveBeenCalledTimes( 1 ); expect( api.postWithToken ).not.toHaveBeenCalled();
	} );
	it.each( [ null, [], {}, { ...request(), owner: '' }, { ...request(), owner: ' Example_owner' }, { ...request(), revisionId: 0 }, { ...request(), revisionId: 2147483648 }, { ...request(), revisionId: '12' }, { ...request(), page: -1 }, { ...request(), page: Infinity }, { ...request(), page: 2147483648 }, { ...request(), binding: 'v1:0:anchor' }, { ...request(), binding: 'v1:77:anchor|v1:77:other' } ] )( 'refuses invalid request %# without transport', async options => {
		const { client, api } = setup( context() ); await expect( client.read( options ) ).rejects.toMatchObject( { code: 'layers-invalid-read-request' } ); expect( api.get ).not.toHaveBeenCalled(); expect( api.postWithToken ).not.toHaveBeenCalled();
	} );
	it.each( [ 'owner', 'revision', 'binding', 'pageId', 'kind', 'label', 'initial', 'count', 'stored', 'inventory order', 'duplicate page', 'duplicate ID', 'member bounds', 'missing anchor', 'wrong anchor', 'missing target', 'target ID', 'source file', 'source pin', 'numeric pin', 'source repository', 'source page', 'surface kind', 'surface label', 'canvas width', 'geometry page', 'geometry width', 'geometry units', 'rendition url', 'rendition dimensions', 'undefined', 'nonfinite', 'sparse', 'cycle', 'accessor', 'custom object', 'symbol', 'metadata infinity' ] )( 'refuses malformed or contradictory %s safely', async kind => {
		const data = context();
		const mutations = { owner: () => { data.owner = 'Other'; }, revision: () => { data.revisionId = 15; }, binding: () => { data.binding = 'v1:77:other'; }, pageId: () => { data.pageId = 78; }, kind: () => { data.kind = 'slide'; }, label: () => { data.label = ''; }, initial: () => { data.initialPage = 4; }, count: () => { data.pageCount = 0; }, stored: () => { data.stored = 1; },
			'inventory order': () => { data.members.push( { page: 1, surfaceId: 'earlier' } ); }, 'duplicate page': () => { data.members.push( { page: 2, surfaceId: 'duplicate' } ); }, 'duplicate ID': () => { data.members.push( { page: 3, surfaceId: 'anchor' } ); }, 'member bounds': () => { data.members.push( { page: 4, surfaceId: 'out' } ); }, 'missing anchor': () => { data.members = []; }, 'wrong anchor': () => { data.members[ 0 ].surfaceId = 'other'; }, 'missing target': () => { data.initialPage = 1; data.members = [ { page: 1, surfaceId: 'anchor' } ]; }, 'target ID': () => { data.surface.id = 'other'; },
			'source file': () => { data.surface.source.fileTitle = 'File:Bad#fragment.pdf'; }, 'source pin': () => { data.surface.source.timestamp = 'latest'; }, 'source repository': () => { data.surface.source.repository = 'foreign'; }, 'source page': () => { data.surface.source.page = 1; }, 'surface kind': () => { data.surface.kind = 'image'; }, 'surface label': () => { data.surface.label = 'Other'; }, 'canvas width': () => { data.surface.canvas.width = 0; }, 'geometry page': () => { data.sourceGeometry.page = 1; }, 'geometry width': () => { data.sourceGeometry.width = -1; }, 'geometry units': () => { data.sourceGeometry.units = 'points'; }, 'rendition url': () => { data.rendition.url = 'javascript:private'; }, 'rendition dimensions': () => { data.rendition.height = 0; },
			undefined: () => { data.extra.bad = undefined; }, nonfinite: () => { data.surface.layers[ 0 ].x = NaN; }, sparse: () => { data.surface.layers.length = 3; }, cycle: () => { data.extra.self = data; }, accessor: () => { Object.defineProperty( data.extra, 'private', { enumerable: true, get: () => { throw new Error( 'secret' ); } } ); }, 'custom object': () => { data.extra = new Date(); }, symbol: () => { data.extra[ Symbol( 'private' ) ] = 'secret'; }, 'metadata infinity': () => { data.surface.metadata.nested.push( Infinity ); } };
		if ( kind === 'numeric pin' ) data.surface.source.timestamp = 20261007120000; else mutations[ kind ](); const { client, api } = setup( data ); await expect( client.read( request() ) ).rejects.toMatchObject( { code: 'layers-reading-failed', message: 'layers-reading-failed' } ); expect( api.get ).toHaveBeenCalledTimes( 1 ); expect( api.postWithToken ).not.toHaveBeenCalled();
	} );
	it.each( [ 'target stored', 'ID stored', 'edited blank' ] )( 'refuses missing-page %s contradictions', async kind => {
		const data = context( false ); if ( kind === 'target stored' ) data.members.unshift( { page: 1, surfaceId: 'other' } ); if ( kind === 'ID stored' ) data.surface.id = 'anchor'; if ( kind === 'edited blank' ) data.surface.layers.push( { id: 'not-blank' } ); const { client, api } = setup( data ); await expect( client.read( { ...request(), page: 1 } ) ).rejects.toMatchObject( { code: 'layers-reading-failed' } ); expect( api.get ).toHaveBeenCalledTimes( 1 ); expect( api.postWithToken ).not.toHaveBeenCalled();
	} );
	it.each( [ 'permissiondenied', 'layers-revision-unavailable', 'layers-reading-failed', 'outofrange', 'unrecognized' ] )( 'redacts server errors and never retries %s', async code => {
		for ( const form of [ 'throw', 'reject', 'response', 'array', 'string' ] ) { const raw = { error: { code, info: 'private path secret' } }, api = { get: jest.fn( () => { if ( form === 'throw' ) throw raw; if ( form === 'response' ) return { ...raw, layersread: { editor: context() } }; return Promise.reject( form === 'array' ? [ code, raw ] : form === 'string' ? code : raw ); } ), postWithToken: jest.fn() }; await expect( new Client( api ).read( request() ) ).rejects.toMatchObject( { code: code === 'unrecognized' ? 'layers-reading-failed' : code, message: code === 'unrecognized' ? 'layers-reading-failed' : code } ); expect( api.get ).toHaveBeenCalledTimes( 1 ); expect( api.postWithToken ).not.toHaveBeenCalled(); }
	} );
	it.each( [ null, {}, { layersread: {} }, { layersread: { editor: null } }, { layersread: { snapshot: {} } } ] )( 'rejects missing editor response %#', async response => { const api = { get: jest.fn().mockResolvedValue( response ) }; await expect( new Client( api ).read( request() ) ).rejects.toMatchObject( { code: 'layers-reading-failed' } ); expect( api.get ).toHaveBeenCalledTimes( 1 ); } );
	it( 'redacts throwing error accessors without leaking the replacement exception', async () => { const error = {}; Object.defineProperty( error, 'code', { get: () => { throw new Error( 'private path secret' ); } } ); const api = { get: jest.fn().mockRejectedValue( error ) }; await expect( new Client( api ).read( request() ) ).rejects.toMatchObject( { code: 'layers-reading-failed', message: 'layers-reading-failed' } ); expect( api.get ).toHaveBeenCalledTimes( 1 ); } );
	it( 'requires an API get method and contains throwing options safely', async () => { expect( () => new Client( {} ) ).toThrow( 'layers-invalid-read-request' ); const { client, api } = setup( context() ), options = {}; Object.defineProperty( options, 'owner', { get: () => { throw new Error( 'private' ); } } ); await expect( client.read( options ) ).rejects.toMatchObject( { code: 'layers-invalid-read-request' } ); expect( api.get ).not.toHaveBeenCalled(); } );
} );